# syntax=docker/dockerfile:1
FROM python:3.12-slim
WORKDIR /srv

# COPY pip.conf /etc/pip.conf
COPY requirements.txt .

# RUN --mount=type=cache,target=/root/.cache/pip \
# pip install -r requirements.txt
RUN pip install -r requirements.txt

COPY . .
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
